# Generated by Django 3.0.7 on 2020-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=50, verbose_name='título')),
                ('content', models.CharField(max_length=50, verbose_name='conteúdo')),
                ('publicacao', models.TextField(max_length=140)),
                ('data_publicacao', models.DateTimeField(auto_now=True, verbose_name='data de publicação')),
                ('categories', models.ManyToManyField(to='core.Category')),
            ],
        ),
    ]
